### ISSUE TITLE
textures not found!

### ISSUE THREAD

**Issue by nahue** [kendo-labs/kendo-rails#1]
I've installed kendoui_rails in rails 3.1 with the asset pipeline enabled, followed all the steps.
When i enter the site... error!

"NetworkError: 404 Not Found - http://localhost:3000/assets/textures/highlight.png"

how can i solve this?? 

thx!

**Comment by bsatrom** [comment]
@nahue,

Sorry about the delay, i _just_ saw this post. I'll take a look.

**Comment by bsatrom** [comment]
Hi @nahue,

I just walked back through all of the steps from scratch, and I'm not getting a 404 on highlight.png --> https://skitch.com/thesatch/8ptap/kendogemtest

Can you try again with the 0.7 version of the gem and let me know how it goes?
