### ISSUE TITLE
kendo.all has been removed?

### ISSUE THREAD

**Issue by Kagetsuki** [kendo-labs/kendo-rails#3]
The gem seems to have had kendo.all removed? We've had to re-add it manually, but why was only kendo.web left in the gem and kendo.all removed?

**Comment by bsatrom** [comment]
Hi Kagetsuki,

This gem provides the current GPLv3 licensed version of Kendo UI Web only.

**Comment by Kagetsuki** [comment]
I'm sorry, then kendo.all is not GPLv3?

**Comment by bsatrom** [comment]
no, since the Q1 release, kendo.all is not provided with Kendo UI Web, commercial or GPL

## 

Brandon Satrom
Sent with Sparrow (http://www.sparrowmailapp.com/?sig)
